config/routes.rb
Rails.application.routes.draw do


  resources :employees

  resources :companies do
    collection { post :import }
  end

  devise_for :users
  get 'static/index'

  get 'static/about'

  get 'static/contact'

  get 'static/faq'

  get 'static/pricing'

  get 'static/features'

  resources :invoices do
      resources :purchases, except: [:index], controller: 'invoices/purchases'
  end

  root to: 'static#index'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enterprise Ape</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<ul class="nav nav-tabs">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About Us", static_about_path %></li>
		<li><%= link_to "Contact", static_contact_path %></li>
		<li><%= link_to "Features", static_features_path %></li>
		<li><%= link_to "FAQ's", static_faq_path %></li>
		<li><%= link_to "Pricing", static_pricing_path %></li>

		<% if current_user %>
			<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			<div class="btn-group pull-right right-nav">
			<button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
				Admin <span class="caret"></span>
			</button>
			<ul class="dropdown-menu" roll="menu">
				<li><%= link_to "Invoices", invoices_path %></li>
				<li><%= link_to "Employees", employees_path %></li>
				<li><%= link_to "Companies", companies_path %></li>
			</ul>
			</div>
		<% else %>
			<li><%= link_to "Sign Up", new_user_registration_path %></li>
			<li><%= link_to "Sign In", new_user_session_path %></li>
		<% end %>
	</ul>

	<% if flash[:notice] %>
		<div class="alert alert-success alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% elsif flash[:error] %>
		<div class="alert alert-error alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:error] %>
		</div>
	<% elsif flash[:alert] %>
		<div class="alert alert-warning alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:alert] %>
		</div>

	<% end %>
	<%= yield %>

</div>
</body>
</html>